### ISSUE TITLE
Description for Value and Milestone objects

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#603]
release-schema.json currently lacks a `description` field for `#definitions/Value`. (See [release-schema.json#L1761](https://github.com/open-contracting/standard/blob/1.1-dev/standard/schema/release-schema.json#L1761) 

Wherever `value` is used, a description exists, so this should not be a major issue for implementations, but it may have some consequences for mapping templates and other tooling.

**Comment by jpmckinney** [comment]
It has also been reported that `#definitions/Milestone` lacks a description.

**Comment by juanpane** [comment]
the release object itself is also missing the description

**Comment by jpmckinney** [comment]
I wrote code to find them all (11):

```
release-schema.json is missing /description
release-schema.json is missing /definitions/Planning/properties/budget/title
release-schema.json is missing /definitions/Planning/properties/budget/description
release-schema.json is missing /definitions/Milestone/description
release-schema.json is missing /definitions/Organization/properties/address/title
release-schema.json is missing /definitions/Organization/properties/address/description
release-schema.json is missing /definitions/Organization/properties/contactPoint/title
release-schema.json is missing /definitions/Organization/properties/contactPoint/description
release-schema.json is missing /definitions/Classification/description
release-schema.json is missing /definitions/Identifier/description
release-schema.json is missing /definitions/Value/description
```

**Comment by jpmckinney** [comment]
Once these are added, I can remove some code in test_json.py that repairs the schema.

**Comment by jpmckinney** [comment]
Oh, and `/definitions/Period/description` is four spaces, so that should be added as well.

**Comment by timgdavies** [comment]
* [x] release-schema.json has a short value for /definitions/Period/description 
* [x] release-schema.json is missing /description
* [x] release-schema.json is missing /definitions/Planning/properties/budget/title
* [x] release-schema.json is missing /definitions/Planning/properties/budget/description
* [x] release-schema.json is missing /definitions/Milestone/description
* [x] release-schema.json is missing /definitions/Organization/properties/address/title
* [x] release-schema.json is missing /definitions/Organization/properties/address/description
* [x] release-schema.json is missing /definitions/Organization/properties/contactPoint/title
* [x] release-schema.json is missing /definitions/Organization/properties/contactPoint/description
* [x] release-schema.json is missing /definitions/Classification/description
* [x] release-schema.json is missing /definitions/Identifier/description
* [x] release-schema.json is missing /definitions/Value/description

**Comment by timgdavies** [comment]
I'm using the following definition for release, building on the text at http://standard.open-contracting.org/latest/en/getting_started/releases_and_records/ and drawing on previous training workshops where we have tried to clarify the nature of release. This change also recognises that this definition could appear in the context of a record package. 

> Each release provides data about a single contracting process at a particular point in time. Releases can be used to notify users of new tenders, awards, contracts and other updates. Releases may repeat or update information provided previously in this contracting process. One contracting process may have many releases. A 'record' of a contracting process follows the same structure as a release, but combines information from multiple points in time into a single summary.

**Comment by timgdavies** [comment]
The following definition is proposed for the `Period` object:

> "Key events during a contracting process may have a known state date, end date, duration, or maximum extent (the latest date the period can extend to). In some cases, not all of these fields will have known or relevant values."

**Comment by timgdavies** [comment]
`planning/budget` description is proposed as:

> "Details of the budget that funds this contracting process."

**Comment by timgdavies** [comment]
For milestones, I've staged the following description:

> "The milestone block can be used to represent a wide variety of events in the lifetime of a contracting process. The milestone type codelist is used to indicate the nature of each milestone." 

This is taken from existing text at http://standard.open-contracting.org/latest/en/schema/codelists/#milestone-type

I considered adding:

> Milestones can be included within the planning, tender, contract and contract implementation blocks. The planning and tender milestone blocks may describe anticipated milestones during the proposed delivery of a contract, as well as key dates from the process of tendering and awarding the contract. The contract milestone block should be used for events related to the signing of the contract documents, with any milestones related to delivery of the contract placed in the contract implementation milestones block.

to respond to the issues in #644, but suggest that would go beyond a bug-fix as it could lead to implications for existing data if #644 surfaces relevant existing use of `Milestones`.

**Comment by timgdavies** [comment]
A definition has been added to Value based on the [current reference documentation text](http://standard.open-contracting.org/latest/en/schema/reference/#value):

> "Financial values should always be published with a currency attached."

**Comment by timgdavies** [comment]
A definition has been added to `Identifier`:

> "A unique identifier for a party (organization)."

**Comment by jpmckinney** [comment]
All definitions look good to me.

**Comment by jpmckinney** [comment]
Closed by #667

**Comment by joelgombin** [comment]
I'm not 100% sure what "a known state date" means exactly?

**Comment by jpmckinney** [comment]
It should be "a known start date" - I'll correct after translation is done. Thanks!

**Comment by joelgombin** [comment]
Ha, thanks !

Le jeu. 22 mars 2018 à 00:50, James McKinney <notifications@github.com> a
écrit :
