### ISSUE TITLE
Add missing documentation on merging

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#771]
I don't see where in the documentation the following OCDS Merge behaviors are prescribed:

* [x] The `id` of the compiledRelease is the `id` of the latest release (#810 #834 set `{ocid}-{date}`)
* [x] The `date` of the compiledRelease is the `date` of the latest release #810 #834 
* [x] The `tag` of the compiledRelease is `["compiled"]` #770 #810
* [x] The `ocid` of the versionedRelease is not versioned (only specified in schema) #810
* [x] The `tag` of the versionedRelease is omitted #770 #810
* [x] If a value in a release is the same as in its preceding release, don't add a versioned object #810

@kindly Did I miss these somewhere?

* [x] As part of this we can clarify precedence, i.e. that `omitWhenMerged` precedes all other rules.

**Comment by kindly** [comment]
@jpmckinney 

> I don't see where in the documentation the following OCDS Merge behaviors are prescribed:
> 
>     * The `id` of the compiledRelease is the `id` of the latest release
>     * The `date` of the compiledRelease is the `date` of the latest release

There was never a rule for these and has been undefined behaviour.  The docs say it should be removed but they can not be removed as `compiledRelease` used the same schema as `release`. #330 will help with this.

> 
>     * The `tag` of the compiledRelease is `["compiled"]` #770
>     * The `ocid` of the versionedRelease is not versioned (only specified in schema)
This looks like the behaviour we want but was not aware it was not documented
> 
>     * The `tag` of the versionedRelease is omitted #770
This is true of `omitWhenMerged`

> 
>     * If a value in a release is the same as in its preceding release, don't add a versioned object
Yes that should be documented
> 
> 
> @kindly Did I miss these somewhere?

I do not think you have.

> 
> As part of this we can clarify precedence, i.e. that `omitWhenMerged` precedes all other rules.

Yes sounds good to me but I think we need #330
