### ISSUE TITLE
Use non-normative language in non-normative sections

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#830]
Following an internal review of documentation, schema, codelists and those of core extensions, we will be more consistent in our use of normative terms, based on our [normative and non-normative content policy](https://docs.google.com/document/d/1xjlAneqgewZvHh6_hwuQ98hbjxRcA2IUqOTJiNGcOf8/edit). Steps anticipated under the policy:

* Clearly mark documentation pages or sections as normative or non-normative. [#846]
* Use RFC 2119 keywords (MUST, SHOULD, MAY, etc.) where appropriate. [this issue]
* Expand the conformance statement with a summary of OCDS norms. [#580]
* Update the Governance page with more detail on versioning. [#674]
* Update the Governance page with detail on how the governance process itself can be updated, including changes to the license and copyright holder of the standard. [#832]

The `must|require|shall|should|recommend|may|optional` (case-insensitive) regular expression can be used to find normative keywords.

**Comment by jpmckinney** [comment]
* [x] Write PR to implement norms review in documentation #831
* [x] Write PR to implement norms review in codelists #852
* [x] Write PR to implement norms review in schema #855
* [x] Write PR to copy/move statements into normative sections if the norm only appears in a non-normative sections
